# toml file with hidden config vars

title = "hidden config vars"

[mf]
user = "j.gunstone"
password = ""

[servers]

[servers.jupyterhub]
ip = "ask abu"
hostname = ""
port = 00
username = ""
password = ""

[servers.mffileserver]
FDIR_SOFTWARE_REMOTE = ""
FDIR_CONDA_BUILD = ""
FDIR_JDRIVE = ""

