# toml file with hidden config vars

title = "hidden config vars"

[mf]
user = "j.gunstone"
password = ""

[servers]

[servers.jupyterhub]
ip = ""
hostname = ""
port = 00
username = ""
password = ""

[servers.mffileserver]
FDIR_SOFTWARE_REMOTE = ""
FDIR_CONDA_BUILD = ""
FDIR_JDRIVE = ""

[cmds]

[cmds.mntconda]
mkdir /mnt/conda-bld
sudo mount -t drvfs '{{ servers.mffileserver.FDIR_CONDA_BUILD }}' /mnt/conda-bld	

[cmds.mntjobs]
mkdir /home/jovyan/jobs
sudo mount -t drvfs '{{ servers.mffileserver.FDIR_JDRIVE }}' /home/jovyan/jobs

[cmds.mntjobsonserver]
mkdir /home/jovyan/jobs
sudo mount -t cifs -o user={{ mf.user }},password={{ mf.password }} {{ servers.mffileserver.FDIR_CONDA_BUILD }} /mnt/conda-bld