name: mfcode_docs
channels:
  - default
  - conda-forge
  - plotly
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - jupyter-book
  - importlib_resources
  - pyppeteer
  - ghp-import
  - numpy
  - seaborn
  - plotly=5.1.0
  - toml
  - pip:
    - PyGEL3D
    - honeybee-energy[standards]