  
title : mfcode developer docs
author: John Gunstone
logo: 'mfcode.png'

# Short description about the book
description: >-
  Developer documentation with a high-level description of Max Fordham engineering development: best-practice, strategy and tools.
execute:
  execute_notebooks           : cache


# Launch button settings
repository:
  url                         : https://github.com/gunstonej/mfcode_docs
  path_to_book                : "book"

