  
title : mfcode developer docs
author: John Gunstone
logo: 'mfcode.png'

# Short description about the book
description: >-
  Developer documentation with a high-level description of Max Fordham engineering development: best-practice, strategy and tools.
execute:
  execute_notebooks           : cache

bibtex_bibfiles:
  - references.bib

# Launch button settings
repository:
  url                         : https://github.com/gunstonej/mfcode_docs
  path_to_book                : "book"

sphinx:
  config:
    latex_elements:
        preamble: |
          \usepackage{longtable}
    bibtex_reference_style: author_year